"""Dealer platform names and domain signatures for website detection."""

from __future__ import annotations

# Platforms to report when detected on a dealer site (order preserved for reference).
DEALER_PLATFORMS: tuple[str, ...] = (
    # Independent dealer / all-in-one platforms
    "DealerSync",
    "Dealr.cloud",
    "DealerCenter",
    "CarsForSale",
    "Dealer Car Search",
    "AutoManager",
    "Frazer DMS",
    "Dealer Essential",
    "FoxDMS",
    "Jouver",
    "Autosoft",
    "Carbase",
    "AAX",
    "AutoStar Solutions",
    "Prime DMS",
    "Wayne Reaves",
    "Dominion DMS",
    "LotWizard",
    "Dealer.com",
    "DealerFX",
    "Cox Automotive",
    "Xtime",
    "AutoWeb",
    "MotoSnap",
    "AutoRevo",
    "Gubagoo",
    "Podium",
    "Fullpath",
    "Convertus",
    "Foureyes",
    "CallRevu",
    # Franchise / enterprise DMS systems
    "CDK Global",
    "Tekion",
    "VinSolutions",
    "DealerSocket",
    "Reynolds & Reynolds",
    "ERA DMS",
    "Ignite DMS",
    "PBS Systems",
    "Dealertrack DMS",
    # Dealer websites / inventory / marketing
    "DealerOn",
    "Dealer Inspire",
    "Dealer eProcess",
    "Jazel Auto",
    "DealerFire",
    "LotLinx",
    "AutoJini",
    "eBizAutos",
    "Team Velocity",
    "AutoSweet",
    "Overfuel",
    "CarNow",
    "CarGurus Digital Deal",
    "AutoLeadStar",
    "AutoFi",
    "Roadster",
    # CRM / lead management
    "Elead CRM",
    "ProMax",
    "DriveCentric",
    "AutoRaptor",
    "Selly Automotive",
    "iMagicLab CRM",
    "Salesforce Automotive",
    "VinCue",
    "Activix CRM",
    # Inventory distribution / merchandising
    "HomeNet Automotive",
    "vAuto",
    "Inventory+",
    "MAX Digital",
    "Rapid Recon",
    "Auction123",
    "Car-Merchant",
    "VINCue Inventory",
    "LotVantage",
    # Buy-here-pay-here (BHPH)
    "Auto Master Systems",
    "Nowcom",
    "DealerClick",
    "AutoZoom",
    "DPC Global",
)

# Domain / HTML markers for platforms without bespoke rules in website_provider.py.
PLATFORM_DOMAINS: dict[str, tuple[str, ...]] = {
    "Dealer Essential": ("dealeressential.com",),
    "FoxDMS": ("foxdms.com",),
    "Jouver": ("jouver.com", "jouver.io"),
    "Autosoft": ("autosoftdms.com", "autosoft.com"),
    "Carbase": ("carbase.com",),
    "AAX": ("aaxsys.com", "aax.com"),
    "AutoStar Solutions": ("autostarsolutions.com",),
    "Prime DMS": ("primedms.com",),
    "Wayne Reaves": ("waynereaves.com",),
    "Dominion DMS": ("dominiondms.com",),
    "LotWizard": ("lotwizard.com",),
    "Dealer.com": ("dealer.com",),
    "DealerFX": ("dealerfx.com",),
    "Cox Automotive": ("coxautoinc.com", "coxautomotive.com"),
    "Xtime": ("xtime.com",),
    "AutoWeb": ("autoweb.com", "dealerweb.com"),
    "MotoSnap": ("motosnap.com",),
    "AutoRevo": ("autorevo.com",),
    "Gubagoo": ("gubagoo.com",),
    "Podium": ("podium.com",),
    "Fullpath": ("fullpath.com", "autoleadstar.com"),
    "Convertus": ("convertus.com",),
    "Foureyes": ("foureyes.io", "foureyes.com"),
    "CallRevu": ("callrevu.com",),
    "Reynolds & Reynolds": ("reynoldsandreynolds.com", "reyrey.com"),
    "ERA DMS": ("eradms.com", "era-dms.com"),
    "Ignite DMS": ("ignitedms.com",),
    "PBS Systems": ("pbssystems.com",),
    "Dealertrack DMS": ("dealertrack.com",),
    "Dealer eProcess": ("dealereprocess.com",),
    "Jazel Auto": ("jazelauto.com",),
    "DealerFire": ("dealerfire.com",),
    "LotLinx": ("lotlinx.com",),
    "AutoJini": ("autojini.com",),
    "eBizAutos": ("ebizautos.com",),
    "Team Velocity": ("teamvelocity.com", "teamvelocitymarketing.com"),
    "AutoSweet": ("autosweet.com",),
    "Overfuel": ("overfuel.com",),
    "CarNow": ("gocarnow.com", "carnow.com"),
    "CarGurus Digital Deal": ("cargurus.com", "digitaldeal.cargurus.com"),
    "AutoLeadStar": ("autoleadstar.com",),
    "AutoFi": ("autofi.com",),
    "Roadster": ("roadster.com",),
    "Elead CRM": ("eleadcrm.com",),
    "ProMax": ("promaxunlimited.com", "promax.com"),
    "DriveCentric": ("drivecentric.com",),
    "AutoRaptor": ("autoraptor.com",),
    "Selly Automotive": ("sellyautomotive.com", "sellyserver.co"),
    "iMagicLab CRM": ("imagiclab.com", "eleadcrm.com"),
    "Salesforce Automotive": ("salesforce.com", "force.com"),
    "VinCue": ("vincue.com",),
    "Activix CRM": ("activix.ca", "activix.com"),
    "HomeNet Automotive": ("homenetiol.com", "homenetautomotive.com"),
    "vAuto": ("vauto.com",),
    "Inventory+": ("inventoryplus.com", "inventoryplus.dealersocket"),
    "MAX Digital": ("maxdigital.com",),
    "Rapid Recon": ("rapidrecon.com",),
    "Auction123": ("auction123.com",),
    "Car-Merchant": ("car-merchant.com", "carmerchant.com"),
    "VINCue Inventory": ("vincue.com",),
    "LotVantage": ("lotvantage.com",),
    "Auto Master Systems": ("automastersystems.com",),
    "Nowcom": ("nowcom.com",),
    "DealerClick": ("dealerclick.com",),
    "AutoZoom": ("autozoom.com",),
    "DPC Global": ("dpcglobal.com",),
}
